spring.application.name=municipios-br
server.port=8080

# URL base da API do IBGE (pode ser sobrescrita em testes)
ibge.api.base-url=https://servicodados.ibge.gov.br/api/v1

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
